state over Server: 3
Server->Jim : update
Server->Sue: update
parallel{
state over Jim: work
state over Sue: work
}
Jim->Server: Commit
state over Server: 4
Sue-->Server: Failed commit
Server->Sue: Update
state over Sue: Resolve conflicts
Sue->Server: Commit
state over Server: 5